### PR TITLE
Docker heroku deploy button

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
A series of edits to enable heroku deploys from a button.

* ~supports multiple MySQL providers (tested on Heroku)~ [REMOVED]
* brings local-dev docker-compose environment
* ~makes redis URL configurable (compatible with Heroku)~ [MOVED TO #46]
* ~adds healthcheck endpoint to verify can talk to mysql & redis (not schema check or OAUTH provider check)~ [MOVED TO #46]
* ~css frontend fix to stop horizontal scrollbars (footer margin)~ [MOVED TO #45]
* ~replaced short tags that do not output `<?` with `<?php`~ [MOVED TO #49]
* This has been tested with multiple Heroku DB providers as well as locally in a docker + docker-compose local-dev environment

~Could do with a clean-up, test suite, change or removal of config.php~ [DONE]

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
## Local Docker health endpoint

Screenshot from 2019-08-17 22-34-59

## Local Docker homepage

Screenshot from 2019-08-17 22-34-52

**Comment by Lewiscowles1986** [comment]
## Heroku deploy homepage

Screenshot from 2019-08-17 22-30-41

## Heroku deploy healthcheck

Screenshot from 2019-08-17 22-31-00

## Heroku deploy other pages

Screenshot from 2019-08-17 22-32-32

Screenshot from 2019-08-17 22-33-23
Screenshot from 2019-08-17 22-33-03
Screenshot from 2019-08-17 22-32-40

Screenshot from 2019-08-17 22-30-55
Screenshot from 2019-08-17 22-30-47

**Comment by Lewiscowles1986** [comment]
I have not yet worked out the MySQL migrations needed to manage from a raw SQL file on Heroku. I have tested locally and you'll notice a Docker compose MySQL container option because of changes to MySQL auth, which are not yet in PHP PDO at the time of writing.

**Comment by Lewiscowles1986** [comment]
healthcheck & CSS changes have been removed and moved into their own PR

**Comment by Lewiscowles1986** [comment]
For now this is blocked on the inclusion of 12-factor PR's #47 or a `config.php` commit (of which I'd strongly recommend one that uses `ENV`).

I've reduced it's size and functionality to provide a pick-and-mix style approach to docker and heroku setup. This is pretty much now only a local docker environment (with docker-compose) and a heroku deploy.

**Comment by Lewiscowles1986** [comment]
I need to check this again before it's committed.

**Comment by aaronpk** [comment]
I've made the changes for config loading from environment variables so it should be possible now to finish this PR. I don't fully understand the current state of this PR though.

**Comment by Lewiscowles1986** [comment]
Chopped into pieces. I'll test soon and get back to you 👍. Last I checked I was waiting on you to explore an alternative ENV loader

**Pull request closed without merging**
